name: Test
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
  schedule:
    # Run every day @9:41. 9:41 chosen randomly.
    - cron: '41 9 * * *'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - "*"
          - "1.14.*"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: "${{ matrix.go-version }}"
      - name: Test
        run: go test -v ./...
