name: Test
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
  schedule:
    # Run every day @9:41. 9:41 chosen randomly.
    - cron: '41 9 * * *'

jobs:
  test:
    name: Go ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: "Latest"
            go-version: '>=1.14.1'
            check-latest: true
          - name: "1.14.1"
            go-version: '1.14.1'
            check-latest: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "${{ matrix.go-version }}"
          check-latest: "${{ matrix.check-latest }}"
      - name: Test
        run: go test -v ./...
